name: Build
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature/actions
jobs:
  publish:
    name: Publish
    runs-on: Gevorg-Win64
    steps:
#      - name: Print Start
#        run: echo "Job Started"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Build Project (Win64)
        run: .\BuildGame.bat
